### ISSUE TITLE
vimspector neovim

### ISSUE THREAD

**Issue by dataO1** [phoityne/hdx4vim#3]
Since a few days vimspector supports neovim (https://www.reddit.com/r/neovim/comments/er1yhd/announcing_vimspector_now_works_in_neovim/).

Trying to run this plugin for nvim I get the following error message in the ghc console drawer:

```
H>>= 
null
[WARNING][REQUEST] Error in $.arguments: When parsing the record StackTraceRequestArguments of type Haskell.DAP.StackTraceRequestArguments the key levels was not present.
null
```

Also the windows look different:
![2020-01-21-225104_1920x2160_scrot](https://user-images.githubusercontent.com/58692022/72846381-c376d400-3ca0-11ea-8f25-6fdf0cccd3ee.png)

Is this a problem with vimspector for neovim or hdx4vim?

**Comment by phoityne** [comment]
Hi.

Regarding parse error,  could you make sure using the latest haskell-debugger?
It's fixed.
 - haskell-debug-adapter-0.0.32.0
 - haskell-dap-0.0.14.0
 - ghci-dap-0.0.13.0


> Also the windows look different:
> Is this a problem with vimspector for neovim or hdx4vim?

It's not a problem of hdx4vim.
hdx4vim does nothing to the GUI.

**Comment by dataO1** [comment]
I installed the newest version for the above 3 dependencies. After i reinstalled them the error did not show up for exactly one time, but after that every time i start the debugger in a fresh terminal i get the same parser error.
Also i get this error, when exiting vim:
```
Channel exit with status 143Error detected while processing function <SNR>145__OnEvent[12]..provider#python3#Call:line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
Invalid channel: 5%   
```
Again i dont know, if this comes from vimspector or the haskell-client.

And regarding the windows, when i said they look weird i meant that the corresponding information doesnt show (like current place in file, stack trace etc., like in your video). That also didnt work for the one time, where the parse error did not appear.
Maybe im missing some configuration for vimspector or something ? i only have the minimal .vimspector.json from here. I only changed the startup file to the main and removed the --test flag from ghci (but it also doesnt work with the original vimspector file).

**Comment by phoityne** [comment]
I think, it looks like neovim + python3 problem.
Could you check python3 provider OK by ":checkhealth" command ?

In my environment(centos7+neovim), it works same with vim.
but, need to import vim module by hand.
```
:packadd vimspector
:python3 import vim
:call vimspector#ToggleBreakpoint()
:call vimspector#Launch()
```

**Comment by dataO1** [comment]
It first didn't work... 
Then I had to set up my laptop again, installed everything from new and it works now.
I dont know what did the trick, but probably as you mentioned i had to install the newest version of hie as well.
