### ISSUE TITLE
Vimspector official support

### ISSUE THREAD

**Issue by puremourning** [phoityne/hdx4vim#4]
Hi there, apologies for opening an issue, i wasn't sure the best way to contact you.

First, thanks so much for documenting how to make Vimspector work with haskell. Very cool!

A user raised https://github.com/puremourning/vimspector/issues/207#issue-658490809 to change vimspector to accept a `null` for `variablesReferences`. I think this is based on your proposed vimspector source modification:

```
$ pwd
/home/phoityne/.vim/pack/vimspector/opt/vimspector/python3/vimspector
$ diff stack_trace.py.dist stack_trace.py
177c177
<     if source.get( 'sourceReference', 0 ) > 0:
---
>     if (source.get( 'sourceReference', 0 ) is not None) and (source.get( 'sourceReference', 0 ) > 0):
$
```

Naturally, i'd prefer users didn't have to modify the vimspector source for it to work, so would it be possible to change the haskell-debug-adapter to _omit_ the key, or supply `0` in accordance with the DAP spec ?

In exchange, i'd love to add "official" support to vimspector's `install_gadget.py` to set up (at least) debug configurations for haskell and document that on the vimspector readme. Typically, vimspector likes to try and install the adapters into a little runtime directory underneath the vimspector install directory. is that possible ? Is there a binary release of haskell-debug-adapter that it could download and put in to it's runtime area ?

**Comment by phoityne** [comment]
Hi.
Thank you for your suggestion, and thanks a lot for the Vimspector.

> would it be possible to change the haskell-debug-adapter to omit the key, or supply 0 in accordance with the DAP spec ?

Yes, now I understand. This is an issue of haskell-debug-adapter.
Unintentionally, it's responding null value. I'll fix it.


> Typically, vimspector likes to try and install the adapters
> into a little runtime directory underneath the vimspector install directory. 
> is that possible ? 

Haskell has some package managers.
For example, "stack" package manager can install binaries to the specified directory.
Does this work for vimspector ?

```
> stack install --local-bin-path=c:\temp haskell-debug-adapter haskell-dap ghci-dap
...
...
...

Copied executables to C:\temp:
  - ghci-dap.exe
  - haskell-dap.exe
  - haskell-debug-adapter.exe

>
```

> Is there a binary release of haskell-debug-adapter that it could download and put in to it's runtime area ?

No, there isn't a binary release.

Regards.

**Comment by puremourning** [comment]
Thanks for the info ! I will try out your command :)

**Comment by phoityne** [comment]
This is fixed and released.
Updated readme.
